### ISSUE TITLE
[BUG] Compiling v0.1.5 fails

### ISSUE THREAD

**Issue by C0D3-M4513R** [Lightcord/Lightcord#214]
**Describe the bug**
When trying to compile the project, using the project's instructions, it fails.

**To Reproduce**
1. Clone this Repo
2. Do a `npm run devInstall`
3. Do a `npm test`

**Expected behavior**
Expected to see the project test correctly, without errors.

**Desktop (please complete the following information):**
 - OS: Arch
 - Version v0.1.5
 - 
**Additional context**
When running `npm test`
```

> lightcord@0.1.5 test
> npm run compile && electron .


> lightcord@0.1.5 compile
> node scripts/compile.js

node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'cross-spawn'
Require stack:
- ~/.cache/yay/lightcord-git/src/lightcord-git/scripts/compile.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/timon/.cache/yay/lightcord-git/src/lightcord-git/scripts/compile.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '~/.cache/yay/lightcord-git/src/lightcord-git/scripts/compile.js'
  ]
}
npm ERR! code 1
npm ERR! path ~.cache/yay/lightcord-git/src/lightcord-git
npm ERR! command failed
npm ERR! command sh -c node scripts/compile.js

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2021-03-13T06_55_29_055Z-debug.log
```
And the debug log file: 
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compile' ]
1 info using npm@7.6.3
2 info using node@v15.11.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:~/.cache/yay/lightcord-git/src/lightcord-git/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:~/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 4ms
19 verbose npm-session 4e9d3c7898873529
20 timing npm:load Completed in 8ms
21 timing command:run Completed in 27ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:378:20)
22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
23 verbose pkgid lightcord@0.1.5
24 verbose cwd ~/.cache/yay/lightcord-git/src/lightcord-git
25 verbose Linux 5.11.5-zen1-1-zen
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
27 verbose node v15.11.0
28 verbose npm  v7.6.3
29 error code 1
30 error path ~/.cache/yay/lightcord-git/src/lightcord-git
31 error command failed
32 error command sh -c node scripts/compile.js
33 verbose exit 1
```

**Potential solution:** 
Add `cross-spawn` to the projects required dependencies.

**Comment by smartfrigde** [comment]
Fixed by latest commits
