### ISSUE TITLE
Electron not works

### ISSUE THREAD

**Issue by FishingHacks** [Lightcord/Lightcord#224]
1: `cd C:\`
2: `git clone https://github.com/Lightcord/Lightcord`
3: `cd Lightcord`
4: `npm run devInstall`
5: `npm test`

Error at execution 5.

Log from Execution 5:

```
> lightcord@0.1.5 test C:\Lightcord
> npm run compile && electron .


> lightcord@0.1.5 compile C:\Lightcord
> node scripts/compile.js


> bandagedbd@0.3.5 build-prod C:\Lightcord\BetterDiscordApp
> webpack --progress --colors --config prod.config.js


> bandagedbd@0.3.5 build C:\Lightcord\BetterDiscordApp
> webpack --progress --colors


> bandagedbd@0.3.5 minify-css C:\Lightcord\BetterDiscordApp
> node minify-css.js


> discord.js-lightcord@11.6.4 build C:\Lightcord\DiscordJS
> tsc


> lightcordapi@1.0.0 build C:\Lightcord\LightcordApi
> webpack --progress --colors


> lightcordapi@1.0.0 build-prod C:\Lightcord\LightcordApi
> webpack --progress --colors --config prod.config.js

10% building 0/1 modules 1 active ...dules\babel-loader\lib\index.js??ref--4!C:\Lightcord\BetterDiscordApp\src\index.jsMinifying...
Minified in 817ms. Minified by 29%
12% building 18/19 modules 1 active C:\Lightcord\LightcordApi\node_modules\babel-loader\lib\index.js??ref--4!C:\Lightcord\LightcordApi\src\alias\react.jsHash: d8de8b639257088e6581
Version: webpack 4.44.1
Time: 21370ms
Built at: 23.03.2021 12:39:39
   Asset      Size  Chunks             Chunk Names
index.js  1.46 MiB    main  [emitted]  main
Entrypoint main = index.js
[./src/0globals.js] 9.47 KiB {main} [built]
[./src/index.js] 1.69 KiB {main} [built]
[./src/loadingIcon.js] 201 bytes {main} [built]
[./src/localStorageFix.js] 1.34 KiB {main} [built]
[./src/modules/bdApi.js] 6.95 KiB {main} [built]
[./src/modules/bdEvents.js] 364 bytes {main} [built]
[./src/modules/classNormalizer.js] 4.91 KiB {main} [built]
[./src/modules/contentManager.js] 13.3 KiB {main} [built]
[./src/modules/core.js] 31 KiB {main} [built]
[./src/modules/dataStore.js] 3.77 KiB {main} [built]
[./src/modules/pluginModule.js] 10.1 KiB {main} [built]
[./src/modules/settingsPanel.js] 18.4 KiB {main} [built]
[./src/modules/themeModule.js] 6.36 KiB {main} [built]
[./src/modules/utils.js] 21.4 KiB {main} [built]
[./src/modules/v2.js] 7.62 KiB {main} [built]
    + 61 hidden modules

WARNING in Circular dependency detected:
src\modules\bdApi.js -> src\modules\core.js -> src\modules\settingsPanel.js -> src\ui\addonlist.jsx -> src\modules\bdApi.js

WARNING in Circular dependency detected:
src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\contentManager.js

WARNING in Circular dependency detected:
src\modules\core.js -> src\modules\settingsPanel.js -> src\ui\addonlist.jsx -> src\modules\bdApi.js -> src\modules\core.js

WARNING in Circular dependency detected:
src\modules\dataStore.js -> src\modules\utils.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\dataStore.js

WARNING in Circular dependency detected:
src\modules\pluginCertifier.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginCertifier.js

WARNING in Circular dependency detected:
src\modules\pluginModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js

WARNING in Circular dependency detected:
src\modules\settingsPanel.js -> src\ui\cssEditor.js -> src\modules\settingsPanel.js

WARNING in Circular dependency detected:
src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\dataStore.js -> src\modules\utils.js -> src\modules\v2.js -> src\modules\themeModule.js

WARNING in Circular dependency detected:
src\modules\utils.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\dataStore.js -> src\modules\utils.js

WARNING in Circular dependency detected:
src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\dataStore.js -> src\modules\utils.js -> src\modules\v2.js

WARNING in Circular dependency detected:
src\ui\addonlist.jsx -> src\modules\bdApi.js -> src\modules\core.js -> src\modules\settingsPanel.js -> src\ui\addonlist.jsx

WARNING in Circular dependency detected:
src\ui\cssEditor.js -> src\modules\settingsPanel.js -> src\ui\cssEditor.js

WARNING in Circular dependency detected:
src\ui\cssEditorDetached.js -> src\modules\settingsPanel.js -> src\ui\cssEditor.js -> src\ui\cssEditorDetached.js

WARNING in Circular dependency detected:
src\ui\tooltip.js -> src\modules\utils.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginCertifier.js -> src\ui\tooltipWrap.js -> src\ui\tooltip.js

WARNING in Circular dependency detected:
src\ui\tooltipWrap.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginCertifier.js -> src\ui\tooltipWrap.js
Hash: 2aea92fc6ccf0bfc3990
Version: webpack 4.44.1
Time: 26545ms
Built at: 23.03.2021 12:39:44
           Asset     Size  Chunks                   Chunk Names
    index.min.js  197 KiB       0  [emitted]        main
index.min.js.map  607 KiB       0  [emitted] [dev]  main
Entrypoint main = index.min.js index.min.js.map
[0] external "electron" 42 bytes {0} [built]
[1] external "path" 42 bytes {0} [built]
[2] external "fs" 42 bytes {0} [built]
[3] external "crypto" 42 bytes {0} [built]
[4] external "node-fetch" 42 bytes {0} [built]
[5] external "events" 42 bytes {0} [built]
[6] external "module" 42 bytes {0} [built]
[7] ./src/index.js + 68 modules 359 KiB {0} [built]
    | ./src/index.js 1.69 KiB [built]
    | ./src/localStorageFix.js 1.34 KiB [built]
    | ./src/loadingIcon.js 201 bytes [built]
    | ./src/0globals.js 9.47 KiB [built]
    | ./src/modules/dataStore.js 3.77 KiB [built]
    | ./src/modules/bdEvents.js 364 bytes [built]
    | ./src/modules/pluginModule.js 10.1 KiB [built]
    | ./src/modules/contentManager.js 13.3 KiB [built]
    | ./src/modules/themeModule.js 6.36 KiB [built]
    | ./src/modules/v2.js 7.62 KiB [built]
    | ./src/modules/utils.js 21.4 KiB [built]
    | ./src/modules/classNormalizer.js 4.91 KiB [built]
    | ./src/modules/settingsPanel.js 18.4 KiB [built]
    | ./src/modules/core.js 31 KiB [built]
    | ./src/modules/bdApi.js 6.95 KiB [built]
    |     + 54 hidden modules

WARNING in Circular dependency detected:
src\modules\bdApi.js -> src\modules\core.js -> src\modules\settingsPanel.js -> src\ui\addonlist.jsx -> src\modules\bdApi.js

WARNING in Circular dependency detected:
src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\contentManager.js

WARNING in Circular dependency detected:
src\modules\core.js -> src\modules\settingsPanel.js -> src\ui\addonlist.jsx -> src\modules\bdApi.js -> src\modules\core.js

WARNING in Circular dependency detected:
src\modules\dataStore.js -> src\modules\utils.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\dataStore.js

WARNING in Circular dependency detected:
src\modules\pluginCertifier.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginCertifier.js

WARNING in Circular dependency detected:
src\modules\pluginModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js

WARNING in Circular dependency detected:
src\modules\settingsPanel.js -> src\ui\cssEditor.js -> src\modules\settingsPanel.js

WARNING in Circular dependency detected:
src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\dataStore.js -> src\modules\utils.js -> src\modules\v2.js -> src\modules\themeModule.js

WARNING in Circular dependency detected:
src\modules\utils.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\dataStore.js -> src\modules\utils.js

WARNING in Circular dependency detected:
src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginModule.js -> src\modules\dataStore.js -> src\modules\utils.js -> src\modules\v2.js

WARNING in Circular dependency detected:
src\ui\addonlist.jsx -> src\modules\bdApi.js -> src\modules\core.js -> src\modules\settingsPanel.js -> src\ui\addonlist.jsx

WARNING in Circular dependency detected:
src\ui\cssEditor.js -> src\modules\settingsPanel.js -> src\ui\cssEditor.js

WARNING in Circular dependency detected:
src\ui\cssEditorDetached.js -> src\modules\settingsPanel.js -> src\ui\cssEditor.js -> src\ui\cssEditorDetached.js

WARNING in Circular dependency detected:
src\ui\tooltip.js -> src\modules\utils.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginCertifier.js -> src\ui\tooltipWrap.js -> src\ui\tooltip.js

WARNING in Circular dependency detected:
src\ui\tooltipWrap.js -> src\modules\v2.js -> src\modules\themeModule.js -> src\modules\contentManager.js -> src\modules\pluginCertifier.js -> src\ui\tooltipWrap.js
Hash: 2b58ec0caa141a5c4758
Version: webpack 4.43.0
Time: 29182ms
Built at: 23.03.2021 12:39:54
                                          Asset        Size  Chunks             Chunk Names
             ..\dist\components\components.d.ts     2.9 KiB          [emitted]
       ..\dist\components\general\AlertBox.d.ts   452 bytes          [emitted]
      ..\dist\components\general\CodeBlock.d.ts   336 bytes          [emitted]
   ..\dist\components\general\ErrorCatcher.d.ts   659 bytes          [emitted]
           ..\dist\components\general\Flex.d.ts    1.31 KiB          [emitted]
         ..\dist\components\general\Margin.d.ts    41 bytes          [emitted]
..\dist\components\general\SettingSubTitle.d.ts   439 bytes          [emitted]
  ..\dist\components\general\SettingsTitle.d.ts   516 bytes          [emitted]
           ..\dist\components\general\Tabs.d.ts   895 bytes          [emitted]
           ..\dist\components\general\Text.d.ts      40 KiB          [emitted]
          ..\dist\components\general\Title.d.ts   436 bytes          [emitted]
        ..\dist\components\general\Tooltip.d.ts   758 bytes          [emitted]
          ..\dist\components\inputs\Button.d.ts    1.29 KiB          [emitted]
     ..\dist\components\inputs\ColorPicker.d.ts   932 bytes          [emitted]
 ..\dist\components\inputs\ColorPicker.old.d.ts   880 bytes          [emitted]
       ..\dist\components\inputs\DateInput.d.ts    2.62 KiB          [emitted]
       ..\dist\components\inputs\DateRange.d.ts  1010 bytes          [emitted]
        ..\dist\components\inputs\Dropdown.d.ts    1.37 KiB          [emitted]
      ..\dist\components\inputs\RadioGroup.d.ts   730 bytes          [emitted]
          ..\dist\components\inputs\Switch.d.ts   614 bytes          [emitted]
        ..\dist\components\inputs\TextArea.d.ts    1.04 KiB          [emitted]
       ..\dist\components\inputs\TextInput.d.ts    1.09 KiB          [emitted]
         ..\dist\components\private\Notice.d.ts   301 bytes          [emitted]
        ..\dist\components\private\Notices.d.ts   962 bytes          [emitted]
                             ..\dist\index.d.ts    10.2 KiB          [emitted]
                 ..\dist\modules\BDModules.d.ts   396 bytes          [emitted]
              ..\dist\modules\DiscordTools.d.ts    4.52 KiB          [emitted]
           ..\dist\modules\PluginUtilities.d.ts   311 bytes          [emitted]
                  ..\dist\modules\Unfreeze.d.ts   191 bytes          [emitted]
                     ..\dist\modules\Utils.d.ts    8.41 KiB          [emitted]
             ..\dist\modules\WebpackLoader.d.ts   404 bytes          [emitted]
            ..\dist\modules\cloneNullProto.d.ts   221 bytes          [emitted]
             ..\dist\modules\environnement.d.ts    84 bytes          [emitted]
         ..\dist\modules\excludeProperties.d.ts   101 bytes          [emitted]
                ..\dist\modules\lazyLoader.d.ts    61 bytes          [emitted]
                      ..\dist\modules\noop.d.ts    39 bytes          [emitted]
                  ..\dist\modules\patchers.d.ts    40 bytes          [emitted]
                  ..\dist\modules\settings.d.ts    1.02 KiB          [emitted]
                      ..\dist\modules\uuid.d.ts   135 bytes          [emitted]
       ..\dist\types\DiscordConstantsTypes.d.ts     226 KiB          [emitted]
      ..\dist\types\DiscordDispatcherTypes.d.ts    1.87 KiB          [emitted]
                                        main.js    2.78 MiB    main  [emitted]  main
Entrypoint main = main.js
[./src/alias/react-dom.js] 593 bytes {main} [built]
[./src/alias/react.js] 486 bytes {main} [built]
[./src/index.ts] 2.02 KiB {main} [built]
[./src/modules/DiscordTools.ts] 5.88 KiB {main} [built]
[./src/modules/Unfreeze.ts] 595 bytes {main} [built]
[./src/modules/Utils.ts] 5.99 KiB {main} [built]
[./src/modules/WebpackLoader.ts] 2.3 KiB {main} [built]
[./src/modules/cloneNullProto.ts] 422 bytes {main} [built]
[./src/modules/environnement.ts] 252 bytes {main} [built]
[./src/modules/excludeProperties.ts] 334 bytes {main} [built]
[./src/modules/lazyLoader.ts] 2.48 KiB {main} [built]
[./src/modules/noop.ts] 125 bytes {main} [built]
[./src/modules/patchers.ts] 11.2 KiB {main} [built]
[./src/modules/settings.ts] 1.55 KiB {main} [built]
[./src/modules/uuid.ts] 287 bytes {main} [built]
    + 308 hidden modules
Hash: 155688e99cf22a211416
Version: webpack 4.43.0
Time: 31224ms
Built at: 23.03.2021 12:39:55
                                          Asset        Size  Chunks                   Chunk Names
             ..\dist\components\components.d.ts     2.9 KiB          [emitted]
       ..\dist\components\general\AlertBox.d.ts   452 bytes          [emitted]
      ..\dist\components\general\CodeBlock.d.ts   336 bytes          [emitted]
   ..\dist\components\general\ErrorCatcher.d.ts   659 bytes          [emitted]
           ..\dist\components\general\Flex.d.ts    1.31 KiB          [emitted]
         ..\dist\components\general\Margin.d.ts    41 bytes          [emitted]
..\dist\components\general\SettingSubTitle.d.ts   439 bytes          [emitted]
  ..\dist\components\general\SettingsTitle.d.ts   516 bytes          [emitted]
           ..\dist\components\general\Tabs.d.ts   895 bytes          [emitted]
           ..\dist\components\general\Text.d.ts      40 KiB          [emitted]
          ..\dist\components\general\Title.d.ts   436 bytes          [emitted]
        ..\dist\components\general\Tooltip.d.ts   758 bytes          [emitted]
          ..\dist\components\inputs\Button.d.ts    1.29 KiB          [emitted]
     ..\dist\components\inputs\ColorPicker.d.ts   932 bytes          [emitted]
 ..\dist\components\inputs\ColorPicker.old.d.ts   880 bytes          [emitted]
       ..\dist\components\inputs\DateInput.d.ts    2.62 KiB          [emitted]
       ..\dist\components\inputs\DateRange.d.ts  1010 bytes          [emitted]
        ..\dist\components\inputs\Dropdown.d.ts    1.37 KiB          [emitted]
      ..\dist\components\inputs\RadioGroup.d.ts   730 bytes          [emitted]
          ..\dist\components\inputs\Switch.d.ts   614 bytes          [emitted]
        ..\dist\components\inputs\TextArea.d.ts    1.04 KiB          [emitted]
       ..\dist\components\inputs\TextInput.d.ts    1.09 KiB          [emitted]
         ..\dist\components\private\Notice.d.ts   301 bytes          [emitted]
        ..\dist\components\private\Notices.d.ts   962 bytes          [emitted]
                             ..\dist\index.d.ts    10.2 KiB          [emitted]
                 ..\dist\modules\BDModules.d.ts   396 bytes          [emitted]
              ..\dist\modules\DiscordTools.d.ts    4.52 KiB          [emitted]
           ..\dist\modules\PluginUtilities.d.ts   311 bytes          [emitted]
                  ..\dist\modules\Unfreeze.d.ts   191 bytes          [emitted]
                     ..\dist\modules\Utils.d.ts    8.41 KiB          [emitted]
             ..\dist\modules\WebpackLoader.d.ts   404 bytes          [emitted]
            ..\dist\modules\cloneNullProto.d.ts   221 bytes          [emitted]
             ..\dist\modules\environnement.d.ts    84 bytes          [emitted]
         ..\dist\modules\excludeProperties.d.ts   101 bytes          [emitted]
                ..\dist\modules\lazyLoader.d.ts    61 bytes          [emitted]
                      ..\dist\modules\noop.d.ts    39 bytes          [emitted]
                  ..\dist\modules\patchers.d.ts    40 bytes          [emitted]
                  ..\dist\modules\settings.d.ts    1.02 KiB          [emitted]
                      ..\dist\modules\uuid.d.ts   135 bytes          [emitted]
       ..\dist\types\DiscordConstantsTypes.d.ts     226 KiB          [emitted]
      ..\dist\types\DiscordDispatcherTypes.d.ts    1.87 KiB          [emitted]
                                    main.min.js     411 KiB       0  [emitted]        main
                        main.min.js.LICENSE.txt   124 bytes          [emitted]
                                main.min.js.map    1.19 MiB       0  [emitted] [dev]  main
Entrypoint main = main.min.js main.min.js.map
  [3] ./src/alias/react.js 486 bytes {0} [built]
 [12] ./src/modules/WebpackLoader.ts 2.3 KiB {0} [built]
 [20] ./src/modules/noop.ts 125 bytes {0} [built]
 [49] ./src/alias/react-dom.js 593 bytes {0} [built]
 [58] ./src/modules/Utils.ts 5.99 KiB {0} [built]
 [73] ./src/modules/uuid.ts 287 bytes {0} [built]
 [88] ./src/modules/cloneNullProto.ts 422 bytes {0} [built]
 [89] ./src/modules/excludeProperties.ts 334 bytes {0} [built]
[100] ./src/modules/DiscordTools.ts 5.88 KiB {0} [built]
[117] ./src/modules/environnement.ts 252 bytes {0} [built]
[120] ./src/index.ts 2.02 KiB {0} [built]
[150] ./src/modules/patchers.ts 11.2 KiB {0} [built]
[151] ./src/modules/Unfreeze.ts 595 bytes {0} [built]
[152] ./src/modules/lazyLoader.ts 2.48 KiB {0} [built]
[153] ./src/modules/settings.ts 1.55 KiB {0} [built]
    + 143 hidden modules
Exiting compilation
C:\Lightcord\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (C:\Lightcord\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (C:\Lightcord\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Lightcord\node_modules\electron\cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR! Test failed.  See above for more details.
```

I have reinstalled electron 5 times.

**Comment by GermanBread** [comment]
`cd C:\`

Are you fucking kidding me

<img src="https://cdn.discordapp.com/emojis/753407551835471942.gif?v=1">

**Comment by ThejominingCraft** [comment]
no :D

**Comment by GermanBread** [comment]
That's almost like installing Linux on NTFS. Unnecessary pain to go though

**Comment by GermanBread** [comment]
Don't cd into the root directory. Just git clone in your home directory.

**Comment by ThejominingCraft** [comment]
I have clone into my development directory, but my name is in the path. because this, i replaced the directory with the root directory

**Comment by GermanBread** [comment]
> I have clone into my development directory, but my name is in the path

What's the issue? Is C:\ the dev directory?

**Comment by ThejominingCraft** [comment]
no. C:\ is the replacement with the dev directory, the issue is that electron does not installed correctly but i don't know why

**Comment by GermanBread** [comment]
npm does not have write permissions for C:\

Like I said, use `git clone` inside your home directory. That'll get you further.

**Comment by GermanBread** [comment]
<h1>e</h1>

**Comment by MoltenCoreDev** [comment]
# big chungus nutsuck among sus

**Comment by DanKGooGLy** [comment]
# **big chungus nutsack among sus**

**Comment by GermanBread** [comment]
> no. C:\ is the replacement with the dev directory, the issue is that electron does not installed correctly but i don't know why

lol my brain farted there. I've seen people find a solution in the Lightcord Discord server maybe that'll get you further

**Comment by GermanBread** [comment]
instead of just substituting your development directory with C:\ you could've just substituted it with [dev directory] or similiar

**Comment by DanKGooGLy** [comment]
ok

**Comment by smartfrigde** [comment]
Try downgrading to node 12
